version: "3.6"

services:
  nginx:
    restart: always
    build:
      context: ${PWD}
      dockerfile: ${PWD}/deployment/Dockerfile
    volumes:
      - ${PWD}/deployment/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8085:80"

  postgres:
    image: postgres
    restart: always
    volumes:
      - ${PWD}/deployment/db_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
      - "8086:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ${PWD}/deployment/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
